// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError('DefaultFirebaseOptions are not supported for this platform.');
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBICEHV-fTofnj0TXOqjuPT5zKXZWxC4Tc',
    appId: '1:494984128352:web:c66ea32fb187b7ff1be005',
    messagingSenderId: '494984128352',
    projectId: 'intern-e290c',
    authDomain: 'intern-e290c.firebaseapp.com',
    databaseURL: 'https://intern-e290c-default-rtdb.firebaseio.com',
    storageBucket: 'intern-e290c.firebasestorage.app',
    measurementId: 'G-P2EEBVBX94',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9uJUkgwbRpnw7kfqSldeGf8t0mC_MAkg',
    appId: '1:494984128352:android:47cd5d79ed3029421be005',
    messagingSenderId: '494984128352',
    projectId: 'intern-e290c',
    databaseURL: 'https://intern-e290c-default-rtdb.firebaseio.com',
    storageBucket: 'intern-e290c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFfbuo-34rpnXJjzbjvThxtnK5Ky0kEBs',
    appId: '1:494984128352:ios:7106d52efb6c1f0e1be005',
    messagingSenderId: '494984128352',
    projectId: 'intern-e290c',
    databaseURL: 'https://intern-e290c-default-rtdb.firebaseio.com',
    storageBucket: 'intern-e290c.firebasestorage.app',
    iosBundleId: 'com.example.intern2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFfbuo-34rpnXJjzbjvThxtnK5Ky0kEBs',
    appId: '1:494984128352:ios:7106d52efb6c1f0e1be005',
    messagingSenderId: '494984128352',
    projectId: 'intern-e290c',
    databaseURL: 'https://intern-e290c-default-rtdb.firebaseio.com',
    storageBucket: 'intern-e290c.firebasestorage.app',
    iosBundleId: 'com.example.intern2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBICEHV-fTofnj0TXOqjuPT5zKXZWxC4Tc',
    appId: '1:494984128352:web:8271883a76fe4df31be005',
    messagingSenderId: '494984128352',
    projectId: 'intern-e290c',
    authDomain: 'intern-e290c.firebaseapp.com',
    databaseURL: 'https://intern-e290c-default-rtdb.firebaseio.com',
    storageBucket: 'intern-e290c.firebasestorage.app',
    measurementId: 'G-EFW10CNNMS',
  );
}
